apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: kavyabhojani/container2:14
        imagePullPolicy: Always
        ports
        - containerPort: 5001
        volumeMounts:
        - mountPath: /kavya_PV_dir
          name: pv-storage
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: kavya-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: LoadBalancer
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 90
      targetPort: 5001
